### ISSUE TITLE
ValidationError

### ISSUE THREAD

**Issue by masato-io** [salespreso/prospyr#1]
Hi, thank you for making this python api tool for ProsperWorks. I'm very new to python but I'm enjoying this api client and I really appreciate your effort on this. Today I encountered an error so I thought I should share via here. 

When I do:
newest_person = Person.objects.order_by('-date_modified')[0]

I get error message below:
ValidationError: ProsperWorks delivered data which does not agree with the local Prospyr schema. This is probably a Prospyr bug. Errors encountered: {'custom_fields': {0: {'value': [u'Not a valid string.']}, 1: {'value': [u'Field may not be null.']}, 2: {'value': [u'Field may not be null.']}, 3: {'value': [u'Field may not be null.']}, 4: {'value': [u'Field may not be null.']}, 5: {'value': [u'Field may not be null.']}, 6: {'value': [u'Field may not be null.']}, 7: {'value': [u'Field may not be null.']}}}

Seems like this error is due to having custom fields in ProsperWorks...?

**Comment by bennullgraham** [comment]
Thanks for the report masato-io. You're correct, custom fields don't work at the moment. I need to think about how to reflect the custom field rules from ProsperWorks in Prospyr without sending constant network requests.

It was silly of me to add definitions for custom fields while they don't work though! For the moment, suggested fix is:
- [x] Temporarily remove fields and validation for "custom fields"
- [x] Expose raw "custom field" data so it can still be handled by users of Prospyr until proper support is added

Does that work for you?

**Comment by bennullgraham** [comment]
The 0.4.0 release removes the half-baked support for custom fields. This prevents this ticket's ValidationError.

If you need access to custom field data, it's provided raw at `_orig_data` on resource instances:

``` python
initrode = Company.objects.get(id=1)
initrode._orig_data
>>>
{'date_created': 1460334523,
 'date_modified': 1460597428,
 'custom_fields': [{'custom_field_definition_id': 12345, 'value': 13}],
 # ...
}
```

**Comment by masato-io** [comment]
Hi @bennullgraham, thanks for the comment and my apology for late response. Yes that works great, appreciated!
