### ISSUE TITLE
Email not showing in ProsperWorks webapp

### ISSUE THREAD

**Issue by saikatbsk** [salespreso/prospyr#7]
The following snippet runs and the Lead is created. But the email is not shown in the web app. Phone number shows.

```
newest_lead = Lead(
    name='Jack',
    emails=[{'email': 'jack@xyz.net', 'category': 'work'}],
    phone_numbers=[{'number': '999-999-9999', 'category': 'mobile'}]
)
```

Same issue while creating Person.

**Comment by bennullgraham** [comment]
Hi saikatbsk,

You need to call `newest_lead.create()` to write Jack to ProsperWorks. Before calling `create()`, Jack only exists in-memory on your local machine.
